### ISSUE TITLE
This API not supported on Android 4.3 and earlier

### ISSUE THREAD

**Issue by aresrioja10** [cprcrack/VideoEnabledWebView#7]
Hola,

Estoy teniendo problemas a la hora de cargar javascript en el WebView. Hasta la versión 4.4.2 el método `loadUrl` funcionaba sin problema. A partir de esta versión falla y encontré el siguiente código en StackOverflow:

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
    webView.evaluateJavascript("function doGetStatePrueba() { " +
    "var state = player1.getState();" +
    "Android.saveState(state);}", null);
} else {
    webView.loadUrl("javascript:function doGetStatePrueba() { " +
    "var state = player1.getState();" +
    "Android.saveState(state);} ");
}
```

En teoría debería funcionar pero el método `evaluateJavascript` no está implementado en tu clase `VideoEnabledWebView`. ¿Puedes ayudarme a implementarlo para que funcione?

El error que aparece es:
`java.lang.IllegalStateException: This API not supported on Android 4.3 and earlier`

Te adjunto también el logcat por si te resulta útil.
```
02-18 10:25:06.420: E/AndroidRuntime(8740): FATAL EXCEPTION: main
02-18 10:25:06.420: E/AndroidRuntime(8740): Process: com.grupoinnovati.educalinecentros, PID: 8740
02-18 10:25:06.420: E/AndroidRuntime(8740): java.lang.IllegalStateException: This API not supported on Android 4.3 and earlier
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at android.webkit.WebViewClassic.evaluateJavaScript(WebViewClassic.java:2669)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at android.webkit.WebView.evaluateJavascript(WebView.java:894)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at com.grupoinnovati.educalinecentros.utils.VideoEnabledWebView.evaluateJavascript(VideoEnabledWebView.java:91)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at com.grupoinnovati.educalinecentros.TareaSeleccionadaActivity.cargarLeccion(TareaSeleccionadaActivity.java:496)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at com.grupoinnovati.educalinecentros.TareaSeleccionadaActivity$2$1.run(TareaSeleccionadaActivity.java:262)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at android.os.Handler.handleCallback(Handler.java:733)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at android.os.Looper.loop(Looper.java:136)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at android.app.ActivityThread.main(ActivityThread.java:5017)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at java.lang.reflect.Method.invoke(Method.java:515)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
02-18 10:25:06.420: E/AndroidRuntime(8740): 	at dalvik.system.NativeStart.main(Native Method)
```

Muchísimas gracias.

**Comment by tianfengjingjing** [comment]
me too ,the os of the phone is Android4.4
